config/routes.rb
Rails.application.routes.draw do
  resources :blogs

  resources :posts
  root 'posts#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  validates :title, :author, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def self.assign_params(*permitted_params)
    define_method :resource_params do
      return [] if request.get?
      if defined?(params_require)
        [params.require(params_require).permit(permitted_params)]
      elsif defined?(resource_request_name)
        [params.require(resource_request_name).permit(permitted_params)]
      else
        [params.require(controller_name.singularize).permit(permitted_params)]
      end
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < InheritedResources::Base
  include InheritedResourcesExt

  assign_params :title, :author
  has_scope :page, :default => 1
  has_scope :per, :default => 10


  def create
    create!
  end

  def update
    update!(service: BlogService, method: :update)
  end

  def destroy
    destroy!(service: BlogService, method: :destroy)
  end
end

app/controllers/posts_controller.rb
class PostsController < InheritedResources::Base
  assign_params :title, :description
  has_scope :page, :default => 1
  has_scope :per, :default => 10
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/blogs/_form.html.slim
= simple_form_for(@blog) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :author

  .form-actions
    = f.button :submit

app/views/blogs/edit.html.slim
h1 Editing blog

== render 'form'

= link_to 'Show', @blog
'|
= link_to 'Back', blogs_path

app/views/blogs/index.html.slim
= index_for(@blogs) do |i|
  = i.attribute :title
  = i.attribute :author
  = i.actions :all

= link_to 'New', new_blog_path(@blog)

app/views/blogs/new.html.slim
h1 New blog

== render 'form'

= link_to 'Back', blogs_path

app/views/blogs/show.html.slim
= show_for(@blog) do |s|
  = s.attribute :title
  = s.attribute :author

= link_to 'Edit', edit_blog_path(@blog)
|
= link_to 'Back', blogs_path

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "ModernRails"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"



  body
    .navbar.navbar-default.navbar-static-top
        .container
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="#"ModernRails
          .navbar-collapse.collapse.navbar-responsive-collapse
            ul.nav.navbar-nav
              li= link_to "Link 1", "/path1"
              li= link_to "Link 2", "/path2"
              li= link_to "Link 3", "/path3"

    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
        .col-lg-3
          .well.sidebar-nav
            h3 Sidebar
            ul.nav.nav-list
              li.nav-header Sidebar
              li= link_to "Link 1", "/path1"
              li= link_to "Link 2", "/path2"
              li= link_to "Link 3", "/path3"

      footer
        p &copy; Company 2014

app/views/posts/_form.html.slim
= simple_form_for(@post) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :description

  .form-actions
    = f.button :submit

app/views/posts/edit.html.slim
h1 Editing post

== render 'form'

= link_to 'Show', @post
'|
= link_to 'Back', posts_path

app/views/posts/index.html.slim
h1 Listing posts

= index_for collection do |p|
  = p.attribute :title
  = p.attribute :description
  = p.actions :all

/ table.table
/   thead
/     tr
/       th Title
/       th Description
/       th
/       th
/       th
/
/   tbody
/     - @posts.each do |post|
/       tr
/         td = post.title
/         td = post.description
/         td = link_to 'Show', post
/         td = link_to 'Edit', edit_post_path(post)
/         td = link_to 'Destroy', post, data: {:confirm => 'Are you sure?'}, :method => :delete

= paginate collection
br
= link_to 'New Post', new_post_path

app/views/posts/new.html.slim
h1 New post

== render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.slim
= show_for resource do |p|
  = p.value :title, wrapper_tag: :h1
  = p.attribute :description

= link_to 'Edit', edit_post_path(@post)
'|
= link_to 'Back', posts_path